// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dogVeterinary.proto

package org.example.grpc;

public interface DogVeterinaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DogVeterinaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
