// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dogVeterinary.proto

package org.example.grpc;

import org.example.DogVeterinaryRequestOrBuilder;

/**
 * Protobuf type {@code DogVeterinaryRequest}
 */
public final class DogVeterinaryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DogVeterinaryRequest)
        DogVeterinaryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DogVeterinaryRequest.newBuilder() to construct.
  private DogVeterinaryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DogVeterinaryRequest() {
    dogName_ = "";
    dogId_ = "";
    ownerId_ = "";
    dateOfCheck_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DogVeterinaryRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.DogVeterinary.internal_static_DogVeterinaryRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.DogVeterinary.internal_static_DogVeterinaryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.DogVeterinaryRequest.class, org.example.DogVeterinaryRequest.Builder.class);
  }

  public static final int DOGNAME_FIELD_NUMBER = 1;
  private volatile Object dogName_;
  /**
   * <code>string dogName = 1;</code>
   * @return The dogName.
   */
  @Override
  public String getDogName() {
    Object ref = dogName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dogName_ = s;
      return s;
    }
  }
  /**
   * <code>string dogName = 1;</code>
   * @return The bytes for dogName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDogNameBytes() {
    Object ref = dogName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dogName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOGID_FIELD_NUMBER = 2;
  private volatile Object dogId_;
  /**
   * <code>string dogId = 2;</code>
   * @return The dogId.
   */
  @Override
  public String getDogId() {
    Object ref = dogId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dogId_ = s;
      return s;
    }
  }
  /**
   * <code>string dogId = 2;</code>
   * @return The bytes for dogId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDogIdBytes() {
    Object ref = dogId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dogId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNERID_FIELD_NUMBER = 3;
  private volatile Object ownerId_;
  /**
   * <code>string ownerId = 3;</code>
   * @return The ownerId.
   */
  @Override
  public String getOwnerId() {
    Object ref = ownerId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ownerId_ = s;
      return s;
    }
  }
  /**
   * <code>string ownerId = 3;</code>
   * @return The bytes for ownerId.
   */
  @Override
  public com.google.protobuf.ByteString
      getOwnerIdBytes() {
    Object ref = ownerId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ownerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFCHECK_FIELD_NUMBER = 4;
  private volatile Object dateOfCheck_;
  /**
   * <code>string dateOfCheck = 4;</code>
   * @return The dateOfCheck.
   */
  @Override
  public String getDateOfCheck() {
    Object ref = dateOfCheck_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dateOfCheck_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOfCheck = 4;</code>
   * @return The bytes for dateOfCheck.
   */
  @Override
  public com.google.protobuf.ByteString
      getDateOfCheckBytes() {
    Object ref = dateOfCheck_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dateOfCheck_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dogName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dogName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dogId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dogId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ownerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfCheck_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dateOfCheck_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dogName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dogName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dogId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dogId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ownerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfCheck_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dateOfCheck_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.DogVeterinaryRequest)) {
      return super.equals(obj);
    }
    org.example.DogVeterinaryRequest other = (org.example.DogVeterinaryRequest) obj;

    if (!getDogName()
        .equals(other.getDogName())) return false;
    if (!getDogId()
        .equals(other.getDogId())) return false;
    if (!getOwnerId()
        .equals(other.getOwnerId())) return false;
    if (!getDateOfCheck()
        .equals(other.getDateOfCheck())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDogName().hashCode();
    hash = (37 * hash) + DOGID_FIELD_NUMBER;
    hash = (53 * hash) + getDogId().hashCode();
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId().hashCode();
    hash = (37 * hash) + DATEOFCHECK_FIELD_NUMBER;
    hash = (53 * hash) + getDateOfCheck().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.DogVeterinaryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.DogVeterinaryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.DogVeterinaryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.DogVeterinaryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.DogVeterinaryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.DogVeterinaryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.DogVeterinaryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DogVeterinaryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DogVeterinaryRequest)
      DogVeterinaryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.DogVeterinary.internal_static_DogVeterinaryRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.DogVeterinary.internal_static_DogVeterinaryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.DogVeterinaryRequest.class, org.example.DogVeterinaryRequest.Builder.class);
    }

    // Construct using org.example.DogVeterinaryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      dogName_ = "";

      dogId_ = "";

      ownerId_ = "";

      dateOfCheck_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.DogVeterinary.internal_static_DogVeterinaryRequest_descriptor;
    }

    @Override
    public org.example.DogVeterinaryRequest getDefaultInstanceForType() {
      return org.example.DogVeterinaryRequest.getDefaultInstance();
    }

    @Override
    public org.example.DogVeterinaryRequest build() {
      org.example.DogVeterinaryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.example.DogVeterinaryRequest buildPartial() {
      org.example.DogVeterinaryRequest result = new org.example.DogVeterinaryRequest(this);
      result.dogName_ = dogName_;
      result.dogId_ = dogId_;
      result.ownerId_ = ownerId_;
      result.dateOfCheck_ = dateOfCheck_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.DogVeterinaryRequest) {
        return mergeFrom((org.example.DogVeterinaryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.DogVeterinaryRequest other) {
      if (other == org.example.DogVeterinaryRequest.getDefaultInstance()) return this;
      if (!other.getDogName().isEmpty()) {
        dogName_ = other.dogName_;
        onChanged();
      }
      if (!other.getDogId().isEmpty()) {
        dogId_ = other.dogId_;
        onChanged();
      }
      if (!other.getOwnerId().isEmpty()) {
        ownerId_ = other.ownerId_;
        onChanged();
      }
      if (!other.getDateOfCheck().isEmpty()) {
        dateOfCheck_ = other.dateOfCheck_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dogName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              dogId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              ownerId_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              dateOfCheck_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object dogName_ = "";
    /**
     * <code>string dogName = 1;</code>
     * @return The dogName.
     */
    public String getDogName() {
      Object ref = dogName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dogName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dogName = 1;</code>
     * @return The bytes for dogName.
     */
    public com.google.protobuf.ByteString
        getDogNameBytes() {
      Object ref = dogName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dogName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dogName = 1;</code>
     * @param value The dogName to set.
     * @return This builder for chaining.
     */
    public Builder setDogName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dogName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dogName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDogName() {
      
      dogName_ = getDefaultInstance().getDogName();
      onChanged();
      return this;
    }
    /**
     * <code>string dogName = 1;</code>
     * @param value The bytes for dogName to set.
     * @return This builder for chaining.
     */
    public Builder setDogNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dogName_ = value;
      onChanged();
      return this;
    }

    private Object dogId_ = "";
    /**
     * <code>string dogId = 2;</code>
     * @return The dogId.
     */
    public String getDogId() {
      Object ref = dogId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dogId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dogId = 2;</code>
     * @return The bytes for dogId.
     */
    public com.google.protobuf.ByteString
        getDogIdBytes() {
      Object ref = dogId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dogId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dogId = 2;</code>
     * @param value The dogId to set.
     * @return This builder for chaining.
     */
    public Builder setDogId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dogId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dogId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDogId() {
      
      dogId_ = getDefaultInstance().getDogId();
      onChanged();
      return this;
    }
    /**
     * <code>string dogId = 2;</code>
     * @param value The bytes for dogId to set.
     * @return This builder for chaining.
     */
    public Builder setDogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dogId_ = value;
      onChanged();
      return this;
    }

    private Object ownerId_ = "";
    /**
     * <code>string ownerId = 3;</code>
     * @return The ownerId.
     */
    public String getOwnerId() {
      Object ref = ownerId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ownerId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ownerId = 3;</code>
     * @return The bytes for ownerId.
     */
    public com.google.protobuf.ByteString
        getOwnerIdBytes() {
      Object ref = ownerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ownerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ownerId = 3;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ownerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = getDefaultInstance().getOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string ownerId = 3;</code>
     * @param value The bytes for ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerId_ = value;
      onChanged();
      return this;
    }

    private Object dateOfCheck_ = "";
    /**
     * <code>string dateOfCheck = 4;</code>
     * @return The dateOfCheck.
     */
    public String getDateOfCheck() {
      Object ref = dateOfCheck_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dateOfCheck_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dateOfCheck = 4;</code>
     * @return The bytes for dateOfCheck.
     */
    public com.google.protobuf.ByteString
        getDateOfCheckBytes() {
      Object ref = dateOfCheck_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dateOfCheck_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOfCheck = 4;</code>
     * @param value The dateOfCheck to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfCheck(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOfCheck_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCheck = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfCheck() {
      
      dateOfCheck_ = getDefaultInstance().getDateOfCheck();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCheck = 4;</code>
     * @param value The bytes for dateOfCheck to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfCheckBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOfCheck_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DogVeterinaryRequest)
  }

  // @@protoc_insertion_point(class_scope:DogVeterinaryRequest)
  private static final org.example.DogVeterinaryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.DogVeterinaryRequest();
  }

  public static org.example.DogVeterinaryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DogVeterinaryRequest>
      PARSER = new com.google.protobuf.AbstractParser<DogVeterinaryRequest>() {
    @Override
    public DogVeterinaryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DogVeterinaryRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DogVeterinaryRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public org.example.DogVeterinaryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

