// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dogVeterinary.proto

package org.example.grpc;

public interface DogVeterinaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DogVeterinaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dogName = 1;</code>
   * @return The dogName.
   */
  String getDogName();
  /**
   * <code>string dogName = 1;</code>
   * @return The bytes for dogName.
   */
  com.google.protobuf.ByteString
      getDogNameBytes();

  /**
   * <code>string dogId = 2;</code>
   * @return The dogId.
   */
  String getDogId();
  /**
   * <code>string dogId = 2;</code>
   * @return The bytes for dogId.
   */
  com.google.protobuf.ByteString
      getDogIdBytes();

  /**
   * <code>string ownerId = 3;</code>
   * @return The ownerId.
   */
  String getOwnerId();
  /**
   * <code>string ownerId = 3;</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();

  /**
   * <code>string dateOfCheck = 4;</code>
   * @return The dateOfCheck.
   */
  String getDateOfCheck();
  /**
   * <code>string dateOfCheck = 4;</code>
   * @return The bytes for dateOfCheck.
   */
  com.google.protobuf.ByteString
      getDateOfCheckBytes();
}
