name: CI/CD Pipeline

on: [push]

jobs:
  test-node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test
      
      
  test-springboot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f microservices/Reservation --batch-mode --update-snapshots package
      - name: Test SpringBoot Upload
        uses: actions/upload-artifact@v3
        with:
          name: SpringBootTests
          path: ./microservices/Reservation/target/surefire-reports/*.txt
      - name: Test SpringBoot Upload
        uses: actions/download-artifact@v3
        with:
          name: SpringBootTests
          
          
  test-quarkus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -f microservices/ReservationDate --batch-mode -DskipTests package
    - name: Run tests
      run: mvn -f microservices/ReservationDate --batch-mode test
      
    - name: Test Quarkus Upload
      uses: actions/upload-artifact@v3
      with:
        name: QuarkusTests
        path: ./microservices/ReservationDate/target/surefire-reports/*.txt
    - name: Test Quarkus Download
      uses: actions/download-artifact@v3
      with:
        name: QuarkusTests
