name: CI/CD Pipeline

on: [push]

jobs:
  test-springboot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f microservices/Reservation --batch-mode --update-snapshots package
      - name: Upload Spring Boot test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResultsSpringBoot
          path: ./microservices/Reservation/target/surefire-reports/*.txt
      - name: Download Spring Boot test results
        uses: actions/download-artifact@v3
        with:
          name: TestResultsSpringBoot
          
          
  test-quarkus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -f microservices/ReservationDate --batch-mode -DskipTests package
    - name: Run tests
      run: mvn -f microservices/ReservationDate --batch-mode test
