#Workflow name
name: CI/CD Pipeline
on: [push]
  #Manually trigger workflow runs
  #workflow_dispatch:
  #Trigger the workflow on push from the main branch
  #push:
  #  paths:
  #    - microservices/Reservation
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
jobs:
  test-springboot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f microservices/Reservation --batch-mode --update-snapshots package
  test-quarkus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn -f microservices/ReservationDate package -DskipTests=true
    - name: Run tests
      run: mvn -f microservices/ReservationDate test
